### ISSUE TITLE
Add rubocop 

### ISSUE THREAD

**Issue by jermnelson** [sul-dlss/infrastructure-integration-test#11]
Add [rubocop](https://github.com/rubocop-hq/rubocop) checking for tests.

**Comment by mjgiarlo** [comment]
@jcoyne Ready? Backlog? Whaddya think?

**Comment by jcoyne** [comment]
I really  don't think that this would be a high priority. I don't care where it goes.

**Comment by mjgiarlo** [comment]
@jcoyne :speech_balloon: 
> I really don't think that this would be a high priority. I don't care where it goes.

In light of that, moving to backlog.

**Comment by ndushay** [comment]
doing this for a stupid simple task in between prescat storage migration testing windows.
