### ISSUE TITLE
Recreate object in stage causing preassembly spec failure

### ISSUE THREAD

**Issue by mjgiarlo** [sul-dlss/infrastructure-integration-test#13]
Possibly caused by the recent rebuilds, our testing object that we use for the preassembly spec got into a bad state. First, it had a defunct version 31, which I chatted with @andrewjbtw about and decided to nuke the defunct version in the workflow service. The test still would not pass for me due to the `Timeout.timeout` block timing out, because the Resque jobs either didn't process or failed. Now the test object is in a new weird state:

```
preservation-ingest-initiated : problem with preservation-ingest-initiated (BackgroundJob: 188970): {:errors=>[{:title=>"Preservation error", :detail=>"Version mismatch in /dor/workspace/bq/653/yd/1233/bq653yd1233/metadata/versionMetadata.xml, expected 32, found 30"}]}
```

**Comment by peetucket** [comment]
Trying to fix by manually editing versionMetadata.xml datastream and file in dor workspace to get it to version 32

**Comment by peetucket** [comment]
Well that didn't work.  Workflow still shows the max version at 30.

**Comment by ndushay** [comment]
If object is unfixable, perhaps we could create a new one and use it???

**Comment by mjgiarlo** [comment]
@ndushay I'm fine with that solution for this issue! As long as the tests all pass.

**Comment by peetucket** [comment]
Re-create test object to fix this
