### ISSUE TITLE
Investigate using a VM for Infrastructure Integration Tests

### ISSUE THREAD

**Issue by jermnelson** [sul-dlss/infrastructure-integration-test#136]
As the Infrastructure team explores using a dedicated VM for running `sdr-deploy` on a shared VM, we may be able to use another VM for running the infrastructure integration tests as various members of the infrastructure team have sub-standard home network speeds that may be causing test failures. The current tests require a browser to run but the VM could run a headless browser for these tests.

**Comment by ndushay** [comment]
Will headless work for javascript?

**Comment by mjgiarlo** [comment]
@ndushay :speech_balloon: 
> Will headless work for javascript?

Yeppers.
