### ISSUE TITLE
Web archiving seed objects need integration tests

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/infrastructure-integration-test#14]
- accessioning seed into SDR for the first time (would this be via was-registrar-app?  via pre-assembly?  both??)
- updating existing SDR web archival seed object

The test should mimic what is done for was seed  object (e.g. start in was-registrar-app?) and should check for was crawl object-ness in Argo. We would like to run something through the was robots if we ca/

Want to test all the way through accessioning (was-robot-suite and common-accessioning) if that is possible, and definitely check for was seed object-ness in Argo.

Talk to Andrew, and ask in web-archiving slack channel.

**Comment by ndushay** [comment]
We also want this to check for existence of thumbnail.

**Comment by justinlittman** [comment]
See https://consul.stanford.edu/display/WARC/Initiating+Seed+Object+Accessioning

**Comment by ndushay** [comment]
- [ ] choose a seed object in the playback portal that is visible (url)
- [ ] register the new seed object  per consul stuff
- [ ] initial workflow set to wasSeedPreassembyWF
- [ ] ensure object got accessioned
- [ ] ensure thumbnail exists
- [ ] check anything else?   structural md?  desc md?
