### ISSUE TITLE
gis-robots accessioned objects need integration tests

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/infrastructure-integration-test#16]
I'm not sure how a GIS object is created and what makes it go thru GIS robots.  Kim Durante or @mejackreed might be able to help.

- creating a new object in SDR (that runs through gis-robots)
- updating a GIS object in SDR

The test should mimic what is done, and should check for GIS object-ness in Argo. All the way through accessioning, if that is possible.

**Comment by mejackreed** [comment]
Perhaps some useful docs:
 - https://consul.stanford.edu/display/SULAIRGIS/GIS+Workflows+Deployment
 - https://consul.stanford.edu/display/SULAIRGIS/Description+of+GIS+robot+workflows
 - https://consul.stanford.edu/display/SULAIRGIS/HOWTO+-+Accession+layers

I think there is an opportunity to reduce some of this codebase as perhaps some of this isn't used.

**Comment by ndushay** [comment]
It may or may not be useful to add a GIS APO and collection object to the dor-services-app seed objects (see sul-dlss/dor-services-app/pull/762)

**Comment by peetucket** [comment]
Note, this is the most useful page of documentation so far: https://consul.stanford.edu/display/SULAIRGIS/HOWTO+-+Accession+layers

Example geo object in prod: https://argo.stanford.edu/view/druid:fz358qb9534

Proposed test script:
* Go to argo-stage/qa, and register a new item
  * Select "file" as content type
  * Enter "GIS Integration Test" as project name (useful for tracking, not required)
  * Select "APO for GIS" as APO
  * Select "Integration Test Collection - GIS" as collection 
  * Enter source ID and label
  * Click register and get DRUID
* On kurma-robots-qa/stage server, copy test content from "/var/geomdtk/current/stage/integration_test_data" to new "druid/temp" based on druid from registration
* On argo-stage/qa, add "gisAssemblyWF" to object, and wait for it to complete
* On argo-stage/qa add "gisDeliveryWF" to object, and wait for it to complete
* On argo-stage/qa add "accessionWF" to object, and wait for it to complete
* Ensure no errors in workflows in argo, check for content type now = "geo"
* Visit PURL, look for some metadata (e.g. label, collection name, "Map data" label?)


To do:
- [ ] figure out why "/var/geomdtk/current/stage" folders do no exist on stage/qa kurma servers
- [ ] get test data in place on kurma-servers 
- [ ] run a manual test with this script and verify it works as expected
