### ISSUE TITLE
Pre-assembly image intergration test is flaky due to variance of image file

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/infrastructure-integration-test#162]
The returned image size in contentMetadata can vary by .1 kb and this messes up the exact matcher.

We could use a regex based matcher to make this less fragile.

https://github.com/sul-dlss/infrastructure-integration-test/blob/master/spec/features/create_preassembly_image_spec.rb#L90-L91

Run 1:
```
     Failure/Error: expect(files.last.text).to eq 'File image.jp2 (image/jp2, 64.1 KB, publish/shelve)'

       expected: "File image.jp2 (image/jp2, 64.1 KB, publish/shelve)"
            got: "File image.jp2 (image/jp2, 64.2 KB, publish/shelve)"
```

Change the exact matcher...and get another failure when it flaps back:

```
     Failure/Error: expect(files.last.text).to eq 'File image.jp2 (image/jp2, 64.2 KB, publish/shelve)'

       expected: "File image.jp2 (image/jp2, 64.2 KB, publish/shelve)"
            got: "File image.jp2 (image/jp2, 64.1 KB, publish/shelve)"
```

**Comment by jcoyne** [comment]
Why does contentMetadata vary? Given that we use the same source, shouldn't it work exactly the same every time?

**Comment by peetucket** [comment]
Not sure.  I believe the value comes from here: https://github.com/sul-dlss/assembly-objectfile/blob/master/lib/assembly-objectfile/object_fileable.rb#L241-L244

Perhaps something to do with the interaction between the ruby File class and the file system, or perhaps some rounding errors in the math done by Ruby converting from the raw value of bytes on disk to kb returned to Ruby?  Or perhaps more likely it really does vary because of the embedded metadata in the exif that varies slightly (like the date) from file to file.
