### ISSUE TITLE
Google Book object needs integration test

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/infrastructure-integration-test#20]
- when the content type is a google book -- make sure everything works all the way thru to argo

**Comment by ndushay** [comment]
talk to Andrew. "What ways do we usually create book objects? Are they created via pre-assembly or not? What are some examples?"  The test should mimic what is done, if there are any special code execution steps taken for books.  If they are just ... objects that come through with no special needs (again, ask Andrew), then this can be closed.

also consider making a separate ticket for updating books if that has any special wrinkles.

**Comment by mjgiarlo** [comment]
@ndushay I re-purposed this issue to focus on the GBook content type like discussed yesterday

**Comment by ndushay** [comment]
It may or may not be useful to add the Google Books APO object to the dor-services-app seed objects (see sul-dlss/dor-services-app/pull/762)

**Comment by edsu** [comment]
From planning: @andrewjbtw asks "do we still need this?". 

From @justinlittman GB is the biggest source of content, but it isn't clear if we can have a meaningful integration test involving the Google Books API. 

We resolved to revisit this if/when we continue GB scanning.
