### ISSUE TITLE
H2: Add PURL Reservation test

### ISSUE THREAD

**Issue by jmartin-sul** [sul-dlss/infrastructure-integration-test#211]
test the reserve-a-PURL functionality

- [ ] in H2 click the `Reserve a PURL` button, enter a title
- [ ] wait a bit, get a PURL
- [ ] turn the registered PURL into an completed deposit
  - [ ] click edit (pencil icon) for the reserved PURL's H2 work
  - [ ] pick a type
  - [ ] fill out the update form (flesh out the metadata and add content, agree to terms, deposit)
- [ ] wait a bit, should be deposited successfully

**Comment by ndushay** [comment]
"reserve a Purl" button ... where?  H2?   Argo??  need a tiny bit more context.

**Comment by ndushay** [comment]
Is this really an integration test, or is it a feature test in H2?   Integration tests are mant for "when I do this in THIS app, then I see the effect properly in this OTHER app"

**Comment by jmartin-sul** [comment]
> Is this really an integration test, or is it a feature test in H2? Integration tests are meant for "when I do this in THIS app, then I see the effect properly in this OTHER app"

There's already a feature test to this effect in H2:  https://github.com/sul-dlss/happy-heron/blob/main/spec/features/purl_reservation_spec.rb

The bugs so far have mostly stemmed from mis-assumptions about inter-service interactions (primarily H2's interactions with sdr-api).  So while the effects might only be tested in the H2 UI, they do depend on interactions with other infra applications.  E.g. the "wait a bit, get a PURL" part of the description spans a call from H2 to sdr-api and a callback from workflow services to H2, which only happens if sdr-api did the right things in the background (after being invoked correctly from H2).    So, I think this is a legit multi-service integration test.

My thinking is basically that if H2 deposit has an integration test, so should PURL reservation.  It spans the same service boundaries, but the interactions differ enough that it seems unsafe to assume that one will work just because the other does.

I could imagine a bit of probing via the Argo UI to confirm that the object in question was registered as expected, and then accessioned as expected.  I hadn't considered that when writing my original description, but said description is vague enough that I think that addendum still fits within it 🙂

**Comment by jmartin-sul** [comment]
> "reserve a Purl" button ... where? H2? Argo?? need a tiny bit more context.

yup, H2, thanks for adding that context!

**Comment by jmartin-sul** [comment]
this is blocked until at least https://github.com/sul-dlss/sdr-api/pull/285 is done, and whatever else it takes to get this feature working initially

**Comment by jmartin-sul** [comment]
with sul-dlss/sdr-api#285 merged, PURL reservation seems to be working, so this is no longer blocked.

**Comment by ndushay** [comment]
@jmartin-sul do you think you could write this in < 60 min?

**Comment by ndushay** [comment]
this can be an H2 ticket in the next work-cycle -- let's try to remember to get it on the board for the next H2 work cycle.
