### ISSUE TITLE
image (non-map?) sort of object needs integration tests

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/infrastructure-integration-test#23]
- not sure if there is a diff between images and maps in how we treat them;  if so, make sure we have tests for each type.

**Comment by ndushay** [comment]
this would NOT be a map;  we do have images as objects;  talk to Andrew.  "What ways do we usually create image objects?  Are they created  via pre-assembly or not?   What are some examples?"

I would also say that we should be trying to write tests for how production works now.

**Comment by aaron-collier** [comment]
@andrewjbtw Can you provide more context as well?

**Comment by jcoyne** [comment]
@ndushay that would require putting files on the `/dor` nfs mount.  I don't believe we have a way to test that, however the sdr-api test allows us to deposit any type of file (including maps and images).

**Comment by andrewjbtw** [comment]
There are a couple of consul pages that mention the map content type as being effectively the same as image.

[Here](https://consul.stanford.edu/display/chimera/DOR+content+types,+resource+types+and+interpretive+metadata
):

> type=map -- an image specialization/categorization, where contents represent maps. Currently treated the same as "image"; may bear additional GIS-related metadata or datastreams. 

And [here](https://consul.stanford.edu/display/chimera/Types+of+DOR+objects+--+object+types+and+content+types)

> map -- an image specialization, where contents represent maps. Currently treated the same as "image" for display.

In pre-assembly there's no choice to select "map" for content type. It also doesn't look like Goobi uses this content type either. So items that are "map" must have that set from either registration or a manual change in Argo. The main maps accessioner seems to be out today, but I'm going to check with her on this.

For GIS data, the content type is "geo".

So I think a test for image will cover maps too unless I hear otherwise.

**Comment by ndushay** [comment]
fine with me - I will close the maps ticket.

**Comment by mjgiarlo** [comment]
@ndushay the Hydrus test uses an image for an item.

here it is deposited: https://github.com/sul-dlss/infrastructure-integration-test/blob/master/spec/features/deposit_via_hydrus_spec.rb#L35-L55

here it is verified to be in argo, associated with its collection: https://github.com/sul-dlss/infrastructure-integration-test/blob/master/spec/features/deposit_via_hydrus_spec.rb#L84-L94

Is there anything you'd add to this?

**Comment by ndushay** [comment]
While it *seems* more efficient to double up on tests, I think it is valuable to have tests clearly indicating what they are testing.

I wouldn't think to test image accessioning with the hydrus test, for example.

Probably worth adding an image accessioning focused test, asking Andrew if there are particular paths folks take (e.g. preassembly or not?) that we should have tests for.

hydrus is its own animal, and if the hydrus test were to stop using an image ... who would think it mattered?

the create_audio (soon to be create_media) object test is the sort of thing I am thinking of.

**Comment by mjgiarlo** [comment]
@ndushay :speech_balloon: 
> 
> Probably worth adding an image accessioning focused test, asking Andrew if there are particular paths folks take (e.g. preassembly or not?) that we should have tests for.

OK, sounds good. Is this actionable---*i.e.*, do you think it's sufficient to copy the media object test and massage it to use an image file?---or should we wait to hear more re: requirements from @andrewjbtw?

**Comment by ndushay** [comment]
I think we want to know more from @andrewjbtw about typical image accessioning - media is its own animal (preassembly settings used are completely different)

**Comment by mjgiarlo** [comment]
OK, moving to backlog.

**Comment by ndushay** [comment]
andrew says:

> I think these are all “typical” and came via pre-assembly https://argo.stanford.edu/catalog?f%5Bis_member_of_collection_ssim%5D%5B%5D=info%3Afedora%2Fdruid%3Axd695sf9329&f%5Bprocessing_status_text_ssi%5D%5B%5D=Accessioned

**Comment by ndushay** [comment]
from Andrew

> I think these are all “typical” and came via pre-assembly https://argo.stanford.edu/catalog?f%5Bis_member_of_collection_ssim%5D%5B%5D=info%3Afedora%2Fdruid%3Axd695sf9329&f%5Bprocessing_status_text_ssi%5D%5B%5D=Accessioned
