### ISSUE TITLE
Add an integration test for opening and closing versions in Argo (and having them go through common accessioning)

### ISSUE THREAD

**Issue by aaron-collier** [sul-dlss/infrastructure-integration-test#233]
Our current reaccessioning tests are pre-assembly based (infrastructure-integration-test). We need a feature test that exercises this functionality through the argo UI.

Why must this be an integration test?”  In this case, it must be an integration test because opening and closing a version is dependent on the state of the object in the workflow.  The workflow is set by the robots, which do not exist in the Argo suite.

- [ ] register and accession an object (or get an accessioned object or ...)
- [ ] View the object
- [ ] Click 'Open for modification'
- [ ] Enter description
- [ ] Click 'close version'
- [ ] Verify that the view page shows the new version with description

**Comment by jcoyne** [comment]
The Argo feature test is here: https://github.com/sul-dlss/argo/pull/2668 That can't test the initial accessioning (using robots) nor the version synch with preservation-catalog, which is why the integration test is also a good idea.
