### ISSUE TITLE
Odd automatic-authentication behavior

### ISSUE THREAD

**Issue by aaron-collier** [sul-dlss/infrastructure-integration-test#237]
Just capturing this ticket for now and can close/update as more information/context is avaialble.

When running integration tests (single or the entire suite) if I change this setting:
https://github.com/sul-dlss/infrastructure-integration-test/blob/main/config/settings.yml#L22 to `true` I have to manually click the "Send me a push" button. This makes it difficult to run these in the background.

**Comment by jcoyne** [comment]
I think that's the intention.  If you have cardinal key installed in the browser, then a push is not needed.
