### ISSUE TITLE
new techmd-service needs integration tests

### ISSUE THREAD

**Issue by justinlittman** [sul-dlss/infrastructure-integration-test#24]
~~Once it becomes visible in Argo (https://github.com/sul-dlss/argo/issues/1824).~~

Blocked by an sdr-api integration test

confirm that it occurs as part of accessioning AND that it does the "right thing".  Maybe something like this??
- API call to tech-md-service for not-yet-accessioned new object is empty
- object accessioned
- API call to tech-md-service for recently accessioned object created tech-md for preserved files and NOT for unpreserved files

**Comment by jermnelson** [comment]
SDR-Client bug Blocking https://github.com/sul-dlss/sdr-client/issues/98
