### ISSUE TITLE
for embargo tests, check xml that would be sent to purl, rather than purl itself

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/infrastructure-integration-test#241]
Thus allowing h2 and hydrus embargo tests to verify the purl xml is correct without needing to go to purl itself, which isn't available in qa.

**Comment by ndushay** [comment]
Mike - is this done now?  Can this ticket be closed?

**Comment by mjgiarlo** [comment]
@ndushay No, not done. Almost have the PR ready but want to be sure the tests are looking good.

**Comment by mjgiarlo** [comment]
Current failure in Hydrus QA test is due to an accessioning problem:

```
    content-metadata-create : Path to object sn816nr3718 not found in any of the root directories: /dor/assembly,/data/hydrus-files,/dor/workspace 
```

**Comment by ndushay** [comment]
that looks like a shared_configs typo with a trailing comma

**Comment by mjgiarlo** [comment]
@ndushay Hmm, I don't see a trailing comma. This is a series of values (an array) joined using a comma. Code: https://github.com/sul-dlss/common-accessioning/blob/0f44e8603f421f23b12fd15b0fffe8efe6d488c8/lib/dor/assembly/path_finder.rb#L13

**Comment by mjgiarlo** [comment]
@ndushay discovered the problem with hydrus-qa: it needs a manual symlink to set up the hydrus-files mount. I don't see an obvious way to automate that, so I am hand-creating it and moving on for now.
