### ISSUE TITLE
Ensure that we can create and then update items without a collection

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/infrastructure-integration-test#256]
Argo allows items without collections and we need to be certain our infrastructure is fine with this.  A test should:
- create an item without a collection and save it and ensure it doesn't error 
- update the item and save it and ensure it doesn't error

It is possible such a test already exists as part of the existing integration tests (or part of one, which could then be added to), or that such a test already exists in Argo.  Please look there first.

It should be sufficient for the item to be registered, and not run through common-accessioning as this test is to ensure the DSA code and our models won't balk if an item has no collections.

It might be possible to do this as an Argo feature test, but I don't feel the calls to DSA should be mocked.  (Maybe use DSA in docker container?? -- this would be a way to start getting more better Argo feature tests and reduce our need for the slow, cranky integration tests)

### Background

This came up while discussing various roundtripping issues with identityMetadata.   More info here https://docs.google.com/document/d/1Oa4bkeLsv9q1kDN_496fRBLguP6VFE79LbxQq6vxeHY/edit#heading=h.9atjs28hu22s and it is also noted here https://github.com/sul-dlss/dor-services-app/issues/2703#issuecomment-829629565

**Comment by ndushay** [comment]
@andrewjbtw is this still something that is done?  Should we add an integration test to ensure we don't break this functionality by accident?

**Comment by andrewjbtw** [comment]
What is the "this"? We're always going to have items that are not in collections, if that's the question. I don't know what motivated this issue. It seems to have come out of discussions of identityMetadata/identification metadata mappings.
