### ISSUE TITLE
Integration tests broken

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/infrastructure-integration-test#29]
May be related to recent changes in dor-services-app: https://github.com/sul-dlss/dor-services-app/pull/726
```
Failed examples:

rspec ./spec/features/reaccession_via_preassembly_spec.rb:21 # Reaccession from preassembly is expected to eq "success"
rspec ./spec/features/create_collection_spec.rb:18 # Use Argo to create a collection is expected to text "Created collection"
rspec ./spec/features/create_object_no_files_spec.rb:17 # Use Argo to create an object without any files is expected to text "Register DOR Items"

```

**Comment by jcoyne** [comment]
The reaccession_via_preassembly, in the downloaded yaml is saying:


```
:message: can't be opened for a new version; cannot re-accession when version > 1
  unless object can be opened
```

The other two are transient

**Comment by jcoyne** [comment]
Transient failures should be fixed with https://github.com/sul-dlss/infrastructure-integration-test/pull/30

**Comment by peetucket** [comment]
Ok, the test object we are using is in an odd state.  I think I can fix that.

How did you see the downloaded yaml file to find that error message?

**Comment by peetucket** [comment]
Huh, fixed the reaccession one by fixing the test object and merged your PR, but there is still one failure (what's a "dead object"?):

```
 1) Use Argo to create a collection
     Failure/Error: click_button 'Send Me a Push'

     Selenium::WebDriver::Error::UnknownError:
       TypeError: can't access dead object

rspec ./spec/features/create_collection_spec.rb:18 # Use Argo to create a collection
```

**Comment by jcoyne** [comment]
I’ve never seen that one before

**Comment by peetucket** [comment]
![i-see-dead-0f06f3947c](https://user-images.githubusercontent.com/47137/76132228-a2efa880-5fc6-11ea-9dbb-23207555667c.jpg)

**Comment by peetucket** [comment]
it was transient... just worked for me
