### ISSUE TITLE
Integration test the IIIF manifest production 

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/infrastructure-integration-test#362]
This will prove that we have sent valid contentMetadata to the access sphere.

After creating an image or book and publishing it, 
then when we go to the purl page (https://purl.stanford.edu/bj118ky1121)
we should find a link to an alternate representation that is a iiif manifest (e.g. `  <link rel="alternate" title="IIIF Manifest" type="application/json" href="https://purl.stanford.edu/bj118ky1121/iiif/manifest" />`
Download and parse that JSON.
At the path `.sequences.[0].canvases.[0].@id` is the URL of a canvas.
We should download that URL and ensure it is valid JSON (e.g. https://purl.stanford.edu/bj118ky1121/iiif/canvas/cocina-fileSet-e9b88116-07a9-4ee5-abcf-2bb5490305a0)

**Comment by mjgiarlo** [comment]
Test image: https://sul-purl-stage.stanford.edu/bg954kx8787
