### ISSUE TITLE
test variants of shelve / publish / preserve settings in accessioning

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/infrastructure-integration-test#42]
these settings are how we do things across systems;  it would be appropriate to have tests to indicate the right things happen for these settings.

we should have tests ensuring that
- preserve = yes puts a file in preservation
- preserve = no does NOT put a file in preservation
- shelve = yes puts the file in stacks (or clearly does the right trigger for getting the file in stacks)
- shelve = no does NOT put the file in stacks
- publish = yes puts the file in purl (or clearly does the right trigger for getting the file in purl) 
- publish = no does NOT put the file in purl

When an object with files with different settings has gone through assembly/common accessioning, viewing the object in argo shows the files and these attributes at the bottom of the page

Given sul-dlss/dor-services-app/4617, this ticket is a "go"

**Comment by mjgiarlo** [comment]
@ndushay Isn't this work done wholly by DSA? If DSA already tests this, do we need an integration test?

**Comment by mjgiarlo** [comment]
Moving to backlog 'til we clarify whether this is integration test-worthy.

**Comment by justinlittman** [comment]
I had the same thought but then I went looking for where we could point to in the DSA codebase that these things were tested and I wasn't coming up with anything clear. (I was only looking at preserve.)

Maybe a first step is to determine where these are currently tested? We might convince ourselves that the testing is adequate or perhaps that additional testing within DSA is necessary or perhaps more integration testing is warranted.
