### ISSUE TITLE
Integration test for web archives accessioning

### ISSUE THREAD

**Issue by lwrubel** [sul-dlss/infrastructure-integration-test#434]
Test the was-registrar-app accessioning and workflows to accession a crawl. Ideally test for eventual appearance in SWAP and Purl. Would need to determine how to clean up after the test or make the collection / crawl unique so that  running of the test does not fail. 

Could rely on a test Archive-It collection if we want to download content or possible setting up with content already downloaded.

**Comment by ndushay** [comment]
See also #14 and #15

**Comment by mjgiarlo** [comment]
TBD to make this ready: document what all steps should be tested.
