### ISSUE TITLE
objects from goobi need integration test

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/infrastructure-integration-test#459]
We would have to start with data for an object _AS IF_ we got it from goobi, with the appropriate workflow step being kicked off.   

Since goobi is another special snowflake that we can break inadvertently, it behooves us to have an integration test to show that given the handoff from goobi to accessioning, everything runs properly and the cocina structural is as expected and object accessions cleanly and looks right in Argo.

To do:
- [ ] figure out why the "integration" goobi user is not seeing the items registered in argo even when the correct project is added
- [ ] figure out how to upload files in goobi and click the various controls that need to be clicked to advance the object there
- [ ] match goobi versions in qa and prod (intranda task)

**Comment by jcoyne** [comment]
As defined, I don't think this is a good integration test.  We really want to test the integration between goobi and SDR, but we don't have goobi available to do that.  By doing a test "AS IF we got it from goobi" we are just turning a relatively fast test in common-accessioning into a slow test here.  There is no systems integration.

**Comment by ndushay** [comment]
@calavano says that he thinks goobi could be hooked up to our stage processes, and a very simple workflow set up ... but the UI uses drag and drop, which could be a problem for Capybara/Selenium.  Dinah is the person to talk to about this.

**Comment by peetucket** [comment]
Questions:
- what is the goobi stage server?
- does the goobi stage server connect to our staging enviroment?
- can we create objects in goobi stage for testing (i.e. we will create fake test data each time we run the integration tests)

**Comment by peetucket** [comment]
Had to change some configuration on goobi-stage, but I was able to successfully register an object in argo-stage, and see it through to goobi, and then export it to complete accessioning:

https://argo-stage.stanford.edu/view/druid:tc097xk0832

**Comment by peetucket** [comment]
Important when registering items (manually or via the integration test in argo):

1. You need to select an APO that has the goobiWF workflow in it.  An APO was created in argo-stage called "[Goobi Testing APO](https://argo-stage.stanford.edu/view/druid:hv879dp7661)" for this purpose.  This APO should be selected when registering items in argo-stage.
2. You need to add the item to a project that is known to Goobi and for which the Goobi user has the project available to work on (as configured in Goobi user management).  A Goobi project called "Integration Testing" was created for this purpose.  This should be entered as the project name when registering in argo-stage.
3. You need to add a specific tag that matches a known "process" in Goobi.  A known process that can be used is called "Accession_Content_Expedited" and thus the exact tag to use when registering items in argo-stage is "DPG : Workflow : Accession_Content_Expedited"
4. Ensure the initial workflow is "goobiWF" in the argo-stage registration form.
5. The label and source ID can be anything.
6. A Goobi user was created in goobi-stage called "integration", this user can be used for integration tests and has the "Integration Testing" project assigned to it, allowing that user to see the items.  The username/password combo for this user will be added to the private config for integration tests if/when we get this working.

See the screen shot below for an example.

![Screen Shot 2022-07-19 at 1 34 06 PM](https://user-images.githubusercontent.com/47137/179862158-2ce26cb7-788e-4993-9279-dd2235178f0e.png)

Once registered, you can find the item in Goobi by searching for the druid that is created in argo.

To do:
- [ ] figure out why the "integration" goobi user is not seeing the items registered in argo even when the correct project is added
- [ ] figure out how to upload files in goobi and click the various controls that need to be clicked to advance the object there

**Comment by ndushay** [comment]
also figure out how to run this test for stage, but not qa.

**Comment by peetucket** [comment]
Yes, given that there is no goobi qa, i think we will just need to skip this particular test if the user is running them in qa
