### ISSUE TITLE
create APO and collection objects for integration test objects

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/infrastructure-integration-test#46]
Our integration tests create a bunch of objects;  it would be handy to use the same APO and collection for those that aren't already spoken for (e.g. ETDs, Hydrus objects, Web Archiving objects).

Andrew will create the APO and the Collection objects, and then tag a developer (probably Naomi) to add these objects to the seeds here:
- https://github.com/sul-dlss/dor-services-app/blob/master/lib/tasks/seeds/druids
   - also needs the foxml, of course

Then the developer will comb through the existing tests that are , for example, using the registration form, and ensure these APO and Collection objects are selected as part of the tests.

**Comment by andrewjbtw** [comment]
@ndushay I've created the collection and APO on stage:

APO: https://argo-stage.stanford.edu/view/druid:qc410yz8746
Collection: https://argo-stage.stanford.edu/view/druid:bc778pm9866

**Comment by ndushay** [comment]
Closing this pre-emptorily;  these PRs should take care of it:

- #52
- sul-dlss/dor-services-app/pull/771
