### ISSUE TITLE
H2 Integration test does not complete

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/infrastructure-integration-test#518]
The shelving step that runs during accessioning may have a race condition and sometimes errors out, but if you manually retry that step in accessionWF in a another window, the object will accession and the test can continue.  We should investigate why the image being accessioned is sometimes not found by the shelving robot.  Seen in both QA and stage

![Screen Shot 2022-11-17 at 12 28 14 PM](https://user-images.githubusercontent.com/47137/202553055-33b113c0-1ba8-4fc5-bc06-5636ae23939f.png)

Possibly happening on the v2 when we test changing embargo

**Comment by justinlittman** [comment]
Actually, it is not being found by pres cat. (The shelving robot asks DSA to shelve. The DSA shelve job checks with pres cat to see what has changed. Pres cat checks the moab on disk, which is out of sync.)

**Comment by peetucket** [comment]
So solution is ... to wait a bit for V1 to catch up before doing a V2? 

Like this:
https://github.com/sul-dlss/infrastructure-integration-test/pull/520

**Comment by peetucket** [comment]
Closed by #520

**Comment by justinlittman** [comment]
Unfortunately, that didn't solve the problem for me.

**Comment by peetucket** [comment]
Currently on the FR board, but I think it could be argued it will be important to have a functional integration test as we work on H2.  I will add it to WC board too.

**Comment by mjgiarlo** [comment]
@peetucket thx

**Comment by mjgiarlo** [comment]
We decided in mid-sprint check-in today that this belongs in the icebox. The FR will look into this and see if they can reproduce it.

**Comment by peetucket** [comment]
Closing again -- hasn't been reported in a while (and I had no problems this week).  Let's re-open if it re-appears.

**Comment by mjgiarlo** [comment]
FWIW, I saw this yesterday in stage while testing moab-versioning changes, but I think we should leave this issue closed until it starts recurring frequently for others.
