### ISSUE TITLE
be able to run tests after stage data has been wiped

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/infrastructure-integration-test#53]
Part of https://github.com/sul-dlss/argo/issues/3947

We have some tests that rely on existing objects in stage

This is fine, but we probably want an easy way to add these objects to stage  when the data has been wiped.
- deposit_via_xslx
- edit_bulk_tags (expects some objects, but isn't too picky about which)
- edit_item_tags (ditto)
- reaccession_from_preassembly

Ideas:
- have a way to register the needed objects as a ?? rake task ?? from this repo
- add these objects to the seeds in dor-services-app
- have tests create the objects they need (bleah)

**Comment by justinlittman** [comment]
I'd consider this as being addressed by https://github.com/sul-dlss/dor-services-app/pull/4567 and https://github.com/sul-dlss/argo/issues/4115#issuecomment-1691902335.

If others determine otherwise, can reopen.
