### ISSUE TITLE
Infra integration test for Globus deposit

### ISSUE THREAD

**Issue by justinlittman** [sul-dlss/infrastructure-integration-test#534]

**Comment by lwrubel** [comment]
The Globus deposit workflow involves getting info from email messages and using the Globus Personal Connect app to upload files. Do we have any examples of these sorts of interactions already to draw from or would the idea be to bypass those steps of the process in some way?

There's a [Globus CLI](https://docs.globus.org/cli/reference/transfer/) that could possibly be used for transferring a file to a particular endpoint--that's a Python package.

**Comment by justinlittman** [comment]
What if we jerry-rigged H2 to always use the same globus endpoint for the integration test? Then we would only need to upload files to globus once.

**Comment by lwrubel** [comment]
Looks like this should have been closed with https://github.com/sul-dlss/happy-heron/pull/2984
