### ISSUE TITLE
integration test for content coming from goobi

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/infrastructure-integration-test#55]
@peetucket may be able to illuminate us on how we might mock the data coming from goobi to then run through the appropriate code (to ... preassemby to common-accessioning?  or to .. dor-services-app? or ...)

ideally, checking that a particular file made it to the fully accessioned object properly (check with andrew or peter for what would be "correct" expectations)

especially need to mimic the way they fill out fields in the registration form (label, sourceid) and what is supposed to be in those fields at the end of the processing (as well as the versioningWF) - @andrewjbtw can you help?

**Comment by jcoyne** [comment]
Whenever we talk about mocking an integration, I think we should pause and see if this is really suitable for additoin to the integration suite.  Ideally we'd have a stage goobi that we could run via user interactions and then test that integration.  If we don't have that, we aren't gaining much by mocking the behavior that goobi has today, if goobi changes their interaction with our system in the future, the system will break, but our integration test won't have caught it and it may give us a false sense of security because we have an "integration test".

**Comment by ndushay** [comment]
@jcoyne you raise a great point.  I wrote this particular ticket in response to Andrew's answer to questions about what we should test:

![image](https://user-images.githubusercontent.com/96775/78323715-8728e500-7527-11ea-82df-4306ff3829f9.png)

This is one of the priority cases he asked us to test.  

The "reaccession via goobi" use case  got broken with the introduction of the version service and how it interacted with accessioning ... so how do you imagine we might do better at avoiding other breakages with the goobi service?   Seems like one good way might be to mimic creating an object using goobi, and also reaccessioning an object using goobi.

Essentially, we're registering or versioning the object however the digilabs would do it, and then submitting a POST request with the kind of data we'd get from goobi.

This is very similar to the ETD situation, where the hydra_etd app becomes aware of an object from a POST request from the registrar.   That POST request was easily mocked.  And the ETD integration test turned out to be a lot more useful than I think you expected.

Similarly, the goobi post can be easily mocked -- we don't have to mock the goobie software, just its final POST request.

**Comment by peetucket** [comment]
We are the process of making goobi's interaction with dor-services-app look exactly the same as pre-assembly's interaction (i.e. a dor-services-app endpoint call): https://github.com/sul-dlss/sul-goobi/issues/258

This is true of single and re-accessioning.  So it may not be important to test goobi separately.

**Comment by ndushay** [comment]
closing this ticket.
