### ISSUE TITLE
Confirm all integration tests pass with Folio as the ILS

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/infrastructure-integration-test#608]
I believe we did this at one time, but it would be good to confirm this during the week of Aug 14

**Comment by justinlittman** [comment]
Confirming that configured to use folio:
* https://github.com/sul-dlss/shared_configs/blob/google-books-qa/config/settings/production.yml#L12
* https://github.com/sul-dlss/shared_configs/blob/sul-hydra-etd-qa/config/settings/production.yml#L26
* https://github.com/sul-dlss/shared_configs/blob/dor-services-app-qa/config/settings/production.yml#L59-L62
* https://github.com/sul-dlss/shared_configs/blob/argo-qa/config/settings/production.yml#L6

**Comment by justinlittman** [comment]
Confirmed.
