### ISSUE TITLE
Ensure GIS item makes it to PURL and EarthWorks

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/infrastructure-integration-test#640]
We should be able to add to the `gis_accessioning_spec` to follow the PURL link and verify that the item is viewable there, and also follow the EarthWorks link to see that it is viewable there as well.

Testing that the item is in EarthWorks may have to be a simple check to make sure the link is 200 OK, but it would be great if there was some way to make sure the viewer was viewing something. But that may require that https://github.com/sul-dlss/sul-embed/issues/2116 be resolved first.

Note: we will need to have the test "Release" the item so that it's available in EarthWorks.

---

From Andrew:
> I checked on the connection in stage and it looks like we actually can push SDR-stage to earthworks-stage. We can't remove from earthworks-stage but new items do appear to show up there. So we could test this as long as each item we test is new (since old items will always be there regardless of whether things are working).

Also from Andrew:

> My understanding has been that as long as 

1. this XML goes out in the public XML
```xml
<releaseData>
<release to="Searchworks">true</release>
<release to="Earthworks">true</release>
</releaseData>
```
2. The rest of the XML is parseable
3. The item/collection does not have a MARC record

then that's as far as SDR infrastructure goes and the item should get picked up by purl-fetcher

More useful background info in #621, particularly pertaining to writing to searchworks.

**Comment by ndushay** [comment]
This may be effectively impossible because it's likely to take many minutes for an object to show up in earthworks.

**Comment by edsu** [comment]
It seems like some kind of suitable wait and following the `View in Earthworks` link on PURL should be doable now? But we would need to fix that link in our staging environment so that it actually goes to EarthWorks in stage?
