### ISSUE TITLE
GIS: add integration test that accessions raster file

### ISSUE THREAD

**Issue by jmartin-sul** [sul-dlss/infrastructure-integration-test#699]
Per standup discussion yesterday: our existing GIS integration tests (`gis_accessioning_spec.rb` and `preassembly_gis_accessioning_spec.rb`) both accession shapefiles, which are vector files.  But the code paths for accessioning vector files and raster files (e.g. GeoTIFFs) diverge somewhat (e.g. a file either goes through `load-vector` or `load-raster` in `gisDeliveryWF`, but not both).  So it'd be nice to have integration tests that exercise both file types/code paths.

Spawned from having to get @kimdurante to do some manual testing for sul-dlss/gis-robot-suite#851, since that modified the way we shell out to system commands for both `load-raster` and `load-vector`.

**Comment by peetucket** [comment]
Example objects to pull fixture data from: 

- https://argo.stanford.edu/view/druid:cb071px1299
- https://argo.stanford.edu/view/druid:fx310pw1401
- https://argo.stanford.edu/view/druid:bb396hs7801

**Comment by peetucket** [comment]
all of the files are original inputs except the ones ending in: fgdc.xml, iso19139.xml, and iso19110.xml
