### ISSUE TITLE
ETD test failing on edtSubmitWF modal

### ISSUE THREAD

**Issue by lwrubel** [sul-dlss/infrastructure-integration-test#709]
`etd_creation_spec.rb` is failing most of the time at the point where it is checking for workflow step completion in the etdSubmitWF.  https://github.com/sul-dlss/infrastructure-integration-test/blob/85f52d9fe36889688d9f183efa91768d3bed1f12/spec/features/etd_creation_spec.rb#L224

We're seeing that when the test clicks on the 'etdSubmitWF' link, it's ending up on the page that is supposed to be loaded as a modal. For example: https://argo-qa.stanford.edu/items/druid:vf465vv3441/workflows/etdSubmitWF. The test can't then close the modal or move on. 

```
Failure/Error:
               within('.modal-dialog') do
                 workflow_done = true if page.has_text?(/register-object\s+completed/) &&
                                         page.has_text?(/submit\s+completed/) &&
                                         page.has_text?(/reader-approval\s+completed/) &&
                                         page.has_text?(/registrar-approval\s+completed/) &&
                                         page.has_text?(/submit-marc\s+completed/, wait: 1) &&
                                         page.has_text?(/check-marc\s+completed/, wait: 1) &&
                                         page.has_text?(/catalog-status\s+waiting/, wait: 1)
     Capybara::ElementNotFound:
       Unable to find visible css ".modal-dialog"
     # ./spec/features/etd_creation_spec.rb:224:in `block (4 levels) in <top (required)>'
     # ./spec/features/etd_creation_spec.rb:222:in `loop'
     # ./spec/features/etd_creation_spec.rb:222:in `block (3 levels) in <top (required)>'
     # ./spec/features/etd_creation_spec.rb:220:in `block (2 levels) in <top (required)>'
```

**Comment by mjgiarlo** [comment]
I was able to reproduce this (in Firefox) but not every time. It happens occasionally on both QA and stage, so it's not clearly env-specific.

**Comment by justinlittman** [comment]
Encountering as well.
